name: Nightwatch Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run Nightwatch tests
      run: npm run ci-test

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: nightwatch-test-results
        path: tests_output/